django_ldap_user_registration/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('dl_user.urls')),
]

dl_user/urls.py
from django.urls import path

from . import views

app_name = 'dl_user'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    path('manage/', views.UserRrAdminManager.as_view(), name='manage'),
    path('manage/<slug:user_id>/', views.AdminUserDetailView.as_view(), name='manage_user_view'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.RegisterSuccessView.as_view(), name='register_success'),
    path('register/activate/<slug:activation_code>/', views.RegisterActivateView.as_view(), name='register_activate'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/success/', views.PasswordResetSuccessView.as_view(), name='password_reset_success'),
    path('password/edit/success/', views.PasswordEditSuccessView.as_view(), name='password_edit_success'),
    path('password/edit/<slug:token>/', views.PasswordEditView.as_view(), name='password_edit'),
    ]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.RegisterSuccessView.as_view(), name='register_success'),
    path('register/activate/<slug:activation_code>/', views.RegisterActivateView.as_view(), name='register_activate'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/success/', views.PasswordResetSuccessView.as_view(), name='password_reset_success'),
    path('password/edit/success/', views.PasswordEditSuccessView.as_view(), name='password_edit_success'),
    path('password/edit/<slug:token>/', views.PasswordEditView.as_view(), name='password_edit'),
    ]

dl_user/models.py
from django.db import models
from django.contrib.auth.models import User


class Institution(models.Model):
    name = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name


class UserRegistrationRecord(models.Model):
    """
        much as we are sending user data to LDAP for registration, we want to keep a history
        of who has registered. We also want to use this table during password reset.
        We use django's built-in user model (User) just to keep data and avoid re-creating fields
        that Django already provides. Note that we are not setting the password fields. We are not
        even keeping the passwords. They belong to LDAP!
    """
    # controls
    reset_code = models.CharField(max_length=255, default='')  # used to hold activation code for registration too
    reset_code_active = models.BooleanField(default=False)
    reset_code_expiry = models.DateTimeField(null=True)
    verified = models.BooleanField(default=False)

    # user data
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ldap_password = models.CharField(max_length=128, blank=True, null=True)
    gender = models.CharField(max_length=10, blank=True, null=True)
    title = models.CharField(max_length=30, blank=True, null=True)
    designation = models.CharField(max_length=200, blank=True, null=True)
    department = models.CharField(max_length=200, blank=True, null=True)
    organization = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=200, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.user.username

dl_user/views.py
from datetime import timedelta

from django.views import generic
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import render, redirect
from django.utils import timezone
from django.urls import reverse_lazy
from django.urls import reverse

from .forms import UserRegisterForm
from .forms import PasswordResetForm
from .forms import PasswordResetEditForm
from .models import UserRegistrationRecord
from .ldap import LDAPOperations
from .passwd import PasswordUtils
from .utils import send_reset_password_email
from .utils import send_newly_registered_email
from .exceptions import AccountActivationException
from .exceptions import PasswordResetException


class IndexView(generic.TemplateView):
    # Index View
    template_name = 'dl_user/home.html'


class RegisterView(generic.FormView):
    template_name = 'dl_user/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('dl_user:register_success')

    def form_valid(self, form):
        passwd_util = PasswordUtils()

        data = form.cleaned_data
        password = passwd_util.mkpasswd(data.get('password'), hash='crypt')

        token = passwd_util.getsalt(length=60)

        # we want to keep record of successful registrations
        user = User.objects.create_user(
            username=data.get('username'),
            email=data.get('email'),
            first_name=data.get('first_name'),
            last_name=data.get('last_name'),
            is_active=False,
        )
        # We keep the user data for later when the user activates the account so we can create it on
        # the LDAP back-end
        user_record = UserRegistrationRecord.objects.create(
            user=user,
            ldap_password=password,
            reset_code=token,
            gender=data.get('gender'),
            title=data.get('title'),
            designation=data.get('designation'),
            department=data.get('department'),
            organization=data.get('organization'),
            phone=data.get('phone'),
            address=data.get('address'),
            country=data.get('country')
        )

        # send notification and activation email alert
        activate_link = settings.SITE_BASE_URL + reverse('dl_user:register_activate', args=[token])
        send_newly_registered_email(user.email, settings.DEFAULT_FROM_EMAIL,
                                    user.get_full_name(), activate_link, settings.IDP_NAME)

        return super().form_valid(form)


class RegisterSuccessView(generic.TemplateView):
    template_name = 'dl_user/register_success.html'


class RegisterActivateView(generic.View):
    def get(self, request, activation_code):
        ldap_ops = LDAPOperations()
        uid_number = str(self.generate_uid_number())
        try:
            user_rr = UserRegistrationRecord.objects.get(reset_code=activation_code)
        except UserRegistrationRecord.DoesNotExist:
            raise AccountActivationException('Invalid activation code')
        user = user_rr.user
        if user.is_active:
            raise AccountActivationException('This account is already active')

        modlist = {
            "objectClass": ["inetOrgPerson", "posixAccount", "shadowAccount"],
            "uid": [user.username],
            "userPassword": [user_rr.ldap_password],
            "sn": [user.last_name],
            "givenName": [user.first_name],
            "cn": [user.get_full_name()],
            "displayName": [user.get_full_name()],
            "title": [user_rr.title],
            "mail": [user.email],
            "employeeType": [user_rr.designation],
            "departmentNumber": [user_rr.department],
            "telephoneNumber": [user_rr.phone],
            "registeredAddress": [user_rr.address],
            "homePhone": [user_rr.phone],
            "uidNumber": [uid_number],
            "gidNumber": [settings.LDAP_GID],
            "loginShell": ["/bin/bash"],
            "homeDirectory": ["/home/users/" + user.username]
        }
        # if this is a CATCH ALL IDP, we need to capture more user attributes since it serves many
        # user organizations and possibly different countries
        if settings.IDP_CATCH_ALL:
            modlist['description'] = ['Organization: ' + user_rr.organization.name,
                                      'Country: ' + user_rr.country]

        result = ldap_ops.add_user(modlist)
        if result:
            # we need to de-activate the code so it can't be re-used and also activate user account just
            # for record purposes since we are not using django's login mechanism anyway
            user_rr.reset_code = ''
            user_rr.save()
            user.is_active = True
            user.save()

        return render(request, 'dl_user/register_activate_success.html', {
            'result': result,
            'message': "Your account is now active!",
        })

    def generate_uid_number(self):
        """
        Find the last record of user. Get UID base and increment by adding the last record pk
        (primary key) and one
        :return: int
        """
        uid_number = settings.LDAP_BASE_UID
        try:
            latest = User.objects.latest('pk')
            uid_number += latest.pk + 1
        except User.DoesNotExist:
            pass

        return uid_number


class PasswordResetView(generic.FormView):
    template_name = 'dl_user/password_reset.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy('dl_user:password_reset_success')

    def form_valid(self, form):
        """
        1. get user by the provided email from db (die silently if there's none)
        2. if exists and is active, send reset email
        :param form:
        :return:
        """
        passwd_util = PasswordUtils()
        email = form.cleaned_data.get('email')
        user = User.objects.get(email=email)
        user_reg_record = UserRegistrationRecord.objects.get(user=user)
        token = passwd_util.getsalt(length=60)  # re-use salt method to generate unique token
        expiry = timezone.now() + timedelta(hours=settings.PASSWORD_RESET_TOKEN_EXPIRY)
        user_reg_record.reset_code = token
        user_reg_record.reset_code_active = True
        user_reg_record.reset_code_expiry = expiry
        user_reg_record.save()

        reset_link = settings.SITE_BASE_URL + reverse('dl_user:password_edit', args=[token])
        # send email
        send_reset_password_email(user.email, settings.DEFAULT_FROM_EMAIL,
                                  user.get_full_name(), reset_link, settings.IDP_NAME)

        return super().form_valid(form)


class PasswordResetSuccessView(generic.TemplateView):
    template_name = 'dl_user/password_reset_success.html'


class PasswordEditView(generic.View):
    template_name = 'dl_user/password_edit.html'

    def get(self, request, token):
        self.check_token_validity(token)
        return render(request, self.template_name, {
            'form': PasswordResetEditForm(),
        })

    def post(self, request, token):
        ldap_ops = LDAPOperations()
        passwd_util = PasswordUtils()
        user_rr = self.check_token_validity(token)

        form = PasswordResetEditForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = user_rr.user.username
            password = passwd_util.mkpasswd(data.get('password'), hash='crypt')

            result = ldap_ops.set_password(username, password)
            if result:
                user_rr.reset_code_expiry = timezone.now()
                user_rr.reset_code = ''
                user_rr.reset_code_active = False
                user_rr.ldap_password = password
                user_rr.save()
                return redirect(reverse('dl_user:password_edit_success'))
            else:
                return render(request, self.template_name, {
                    'form': form,
                    'ldap_error': 'Password reset failed on LDAP server. Contact admin'
                })
        else:
            return render(request, self.template_name, {
                'form': form,
            })

    def check_token_validity(self, token):
        try:
            user_rr = UserRegistrationRecord.objects.get(reset_code=token,
                                                         reset_code_active=True,
                                                         reset_code_expiry__gt=timezone.now())
        except UserRegistrationRecord.DoesNotExist:
            raise PasswordResetException('Password reset link invalid or expired')
        return user_rr


class PasswordEditSuccessView(generic.TemplateView):
    template_name = 'dl_user/password_edit_success.html'


class UserRrAdminManager(generic.ListView):
    """
    Provides an interface for managing the signed up users. Admin can approve/deny sign-up requests
    """
    model = UserRegistrationRecord
    paginate_by = 50


class AdminUserDetailView(generic.DetailView):
    model = UserRegistrationRecord

dl_user/templates/dl_user/base.html
{% extends 'dl_user/bootstrap.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% block bootstrap3_content %}
{% url 'dl_user:register' as register_url %}
{% url 'dl_user:password_reset' as password_reset_url %}
    <nav class="navbar navbar-inverse">
	<div class="container">
	    <div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		    <span class="sr-only">Toggle navigation</span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		</button>
                <a class="navbar-brand" href="{% url 'dl_user:home' %}">{{ settings.IDP_NAME }} User Support</a>
	    </div>
	    <div id="navbar" class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
                    <!-- navigation can be extended in future if needed >
		    <li class="active"><a href="{% url 'dl_user:home' %}">Home</a></li>
		    <li><a href="{% url 'dl_user:register' %}">Register</a></li>
		    <li><a href="{% url 'dl_user:password_reset' %}">Change password</a></li>
                    -->
		</ul>
	    </div><!-- /.nav-collapse -->
	</div><!-- /.container -->
    </nav><!-- /.navbar -->
    <div class="container">
	<div class="jumbotron">
            {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
	    <a href="{% url 'dl_user:home' %}"><img class="img-fluid" src="{{settings.IDP_LOGO}}" alt="{{settings.IDP_NAME}}" /></a>
    {% block content %}
    {% endblock %}
{% endblock %}
{% bootstrap_javascript %}

dl_user/templates/dl_user/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

dl_user/templates/dl_user/home.html
{% extends 'dl_user/base.html' %}
{% load bootstrap3 %}
{% block bootstrap3_title %}{{ settings.IDP_NAME }} User Support{% endblock %}
{% block content %}
            <h2>{{ settings.IDP_NAME }} User Support</h2>
	    <p>Don't have a Federated Identity yet? Proceed and register below</p>
	</div>
	<div class="row">
	    <div class="col-xs-6 col-lg-6">
		<h3>Registration of a new account</h3>
                {% bootstrap_button "Register" button_type="link" size="lg" button_class="btn-success" icon="user" href=register_url %}
	    </div>
	    <div class="col-xs-6 col-lg-6">
		<h3>Servicing an existing account</h3>
                {% bootstrap_button "Forgotten password" button_type="link" size="lg" button_class="btn-warning" icon="question-sign" href=password_reset_url %}
                {% bootstrap_button "Password change" button_type="link" size="lg" button_class="btn-warning" icon="info-sign" href=password_reset_url %}
	    </div>
	</div>
	<hr>
	<footer>
	    <p>If you already have a Federated ID, you can test your login credentials at:
                {% bootstrap_button settings.SERVICE_PROVIDER button_type="link" size="sm" href=settings.SERVICE_PROVIDER_URL %}
	    </p>
	</footer>
{% endblock %}

dl_user/templates/dl_user/password_edit.html
{% extends "dl_user/base.html" %}
{% block bootstrap3_title %}Enter New Password{% endblock %}
{% block content %}
        <h2>Password Edit</h2>
</div>
<div class="col-md-6">
    {% if ldap_error %}
    <div class="alert alert-danger">
        {{ ldap_error }}
    </div>
    {% endif %}
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

dl_user/templates/dl_user/password_edit_success.html
{% extends "dl_user/base.html" %}
{% load bootstrap3 %}
{% block bootstrap3_title %}Password edited successfully{% endblock %}
{% block content %}
        <h2>Password Edit</h2>
        <p>Your password has been successfully updated. Test your login credentials at <a href="{{settings.SERVICE_PROVIDER_URL}}">{{settings.SERVICE_PROVIDER}}</a></p>
</div>
{% endblock %}

dl_user/templates/dl_user/password_reset.html
{% extends "dl_user/base.html" %}
{% block bootstrap3_title %}Reset Password{% endblock %}
{% block content %}
        <h2>Password Reset for {{ settings.IDP_NAME }}</h2>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

dl_user/templates/dl_user/password_reset_success.html
{% extends "dl_user/base.html" %}
{% load bootstrap3 %}
{% block bootstrap3_title %}Password reset sent{% endblock %}
{% block content %}
    <h2>Password change / reset</h2>
    {% bootstrap_alert "A link has been sent to the email you provided. Follow the instructions" alert_type="info" dismissable=False %}
</div>
{% endblock %}

dl_user/templates/dl_user/register.html
{% extends "dl_user/base.html" %}
{% block bootstrap3_title %}Create an account{% endblock %}
{% block content %}
    <h2>Registering a new account</h2>
    <p>You are registering to the {{ settings.IDP_NAME }}</p>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
        <ul>
		    {% for field in form %}
			{% if field.errors %}<li><i>{{ field.label }}</i>: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
		</ul>
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

dl_user/templates/dl_user/register_activate_success.html
{% extends "dl_user/base.html" %}
{% load bootstrap3 %}¬
{% block bootstrap3_title %}Account activation success!{% endblock %}
{% block content %}
    <h2 class="text-success">{{ message }}</h2>
    <p>Please proceed to <a href="{{ settings.SERVICE_PROVIDER_URL }}">{{ settings.SERVICE_PROVIDER }}</a> to try out your login credentials</p>
</div>
{% endblock %}

dl_user/templates/dl_user/register_success.html
{% extends "dl_user/base.html" %}
{% load bootstrap3 %}
{% block bootstrap3_title %}Account creation success!{% endblock %}
{% block content %}
    <h2>Success!</h2>
    <p>Now you need to confirm registration</p>
    {% bootstrap_alert "A verification email has been sent to your account. Please follow instructions according to the email content." alert_type="info" dismissable=False %}
</div>
{% endblock %}

dl_user/templates/dl_user/userregistrationrecord_detail.html
safdasf

dl_user/templates/dl_user/userregistrationrecord_list.html
{% extends "dl_user/base.html" %}
{% block bootstrap3_title %}Manage user registration records{% endblock %}
{% block content %}
        <h2>User Registration Records</h2>
</div>
<table class="table">
    <thead>
    <tr>
        <th>&nbsp;</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Verified</th>
        <th>Active</th>
        <th>Gender</th>
        <th>Organization</th>
        <th>Title</th>
        <th>Designation</th>
        <th>Department</th>
        <th>Address</th>
    </tr>
    </thead>
    <tbody>
    {% for user in object_list %}
    <tr>
        <td>
            {{ forloop.counter }}
        </td>
        <td>
            <a href="{% url 'dl_user:manage_user_view' user.pk %}">
                {{ user.user.first_name }}
            </a>
        </td>
        <td>{{ user.user.last_name }}</td>
        <td>{{ user.user.email }}</td>
        <td>
            {% if user.verified %}
            Yes
            {% else %}
            No
            <button type="button" class="btn btn-success btn-xs" aria-label="Verify" title="Manually verify email">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                Verify
            </button>
            {% endif %}
        </td>
        <td>
            {% if user.user.is_active %}
            Yes
            {% else %}
            No
            {% if user.verified %}
            {# Show button to activate only if user account is verified #}
            <button type="button" class="btn btn-warning btn-xs" aria-label="Activate" title="Activate">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                Activate
            </button>
            {% endif %}
            {% endif %}
        </td>
        <td>
            {% if user.gender %}
            Male
            {% else %}
            Female
            {% endif %}
        </td>
        <td>{{ user.organization }}</td>
        <td>{{ user.title }}</td>
        <td>{{ user.designation }}</td>
        <td>{{ user.department }}</td>
        <td>{{ user.address }}</td>
    </tr>
    {% empty %}
    <tr><td colspan="9" align="center"><h3>No users yet</h3></td></tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}