django_ldap_user_registration/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('dl_user.urls')),
]

user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('register/success/', views.RegisterSuccessView.as_view(), name='register_success'),
    path('register/activate/<slug:activation_code>/', views.RegisterActivateView.as_view(), name='register_activate'),
    path('password/reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password/reset/success/', views.PasswordResetSuccessView.as_view(), name='password_reset_success'),
    path('password/edit/success/', views.PasswordEditSuccessView.as_view(), name='password_edit_success'),
    path('password/edit/<slug:token>/', views.PasswordEditView.as_view(), name='password_edit'),
    ]

user/views.py
from datetime import timedelta

from django.views import generic
from django.contrib.auth.models import User
from django.conf import settings
from django.shortcuts import render, redirect
from django.utils import timezone

from .forms import UserRegisterForm
from .forms import PasswordResetForm
from .forms import PasswordResetEditForm
from .models import UserRegistrationRecord
from .ldap import LDAPOperations
from .passwd import PasswordUtils
from .utils import send_reset_password_email
from .utils import send_newly_registered_email
from .exceptions import AccountActivationException
from .exceptions import PasswordResetException


class IndexView(generic.TemplateView):
    # Index View
    template_name = 'user/index.html'


class RegisterView(generic.FormView):
    template_name = 'user/register.html'
    form_class = UserRegisterForm
    success_url = '/user/register/success/'

    def form_valid(self, form):
        passwd_util = PasswordUtils()

        data = form.cleaned_data
        password = passwd_util.mkpasswd(data.get('password'), hash='crypt')

        token = passwd_util.getsalt(length=60)

        # we want to keep record of successful registrations
        user = User.objects.create_user(
            username=data.get('username'),
            email=data.get('email'),
            first_name=data.get('first_name'),
            last_name=data.get('last_name'),
            is_active=False,
        )
        # We keep the user data for later when the user activates the account so we can create it on
        # the LDAP back-end
        user_record = UserRegistrationRecord.objects.create(
            user=user,
            ldap_password=password,
            reset_code=token,
            gender=data.get('gender'),
            title=data.get('title'),
            designation=data.get('designation'),
            department=data.get('department'),
            organization=data.get('organization'),
            phone=data.get('phone'),
            address=data.get('address'),
            country=data.get('country')
        )

        # send notification and activation email alert
        activate_link = settings.SITE_BASE_URL + '/user/register/activate/' + token + '/'

        send_newly_registered_email(user.email, settings.DEFAULT_FROM_EMAIL,
                                  user.get_full_name(), activate_link, settings.IDP_NAME)

        return super().form_valid(form)


class RegisterSuccessView(generic.TemplateView):
    template_name = 'user/register_success.html'


class RegisterActivateView(generic.View):
    def get(self, request, activation_code):
        ldap_ops = LDAPOperations()
        uid_number = str(self.generate_uid_number())
        try:
            user_rr = UserRegistrationRecord.objects.get(reset_code=activation_code)
        except UserRegistrationRecord.DoesNotExist:
            raise AccountActivationException('Invalid activation code')
        user = user_rr.user
        if user.is_active:
            raise AccountActivationException('This account is already active')

        modlist = {
            "objectClass": ["inetOrgPerson", "posixAccount", "shadowAccount"],
            "uid": [user.username],
            "userPassword": [user_rr.ldap_password],
            "sn": [user.last_name],
            "givenName": [user.first_name],
            "cn": [user.get_full_name()],
            "displayName": [user.get_full_name()],
            "title": [user_rr.title],
            "mail": [user.email],
            "employeeType": [user_rr.designation],
            "departmentNumber": [user_rr.department],
            "telephoneNumber": [user_rr.phone],
            "registeredAddress": [user_rr.address],
            "homePhone": [user_rr.phone],
            "uidNumber": [uid_number],
            "gidNumber": [settings.LDAP_GID],
            "loginShell": ["/bin/bash"],
            "homeDirectory": ["/home/users/" + user.username]
        }
        # if this is a CATCH ALL IDP, we need to capture more user attributes since it serves many
        # user organizations and possibly different countries
        if settings.IDP_CATCH_ALL:
            modlist['description'] = ['Organization: ' + user_rr.organization.name,
                                      'Country: ' + user_rr.country]

        result = ldap_ops.add_user(modlist)
        if result:
            # we need to de-activate the code so it can't be re-used and also activate user account just
            # for record purposes since we are not using django's login mechanism anyway
            user_rr.reset_code = ''
            user_rr.save()
            user.is_active = True
            user.save()

        return render(request, 'user/register_activate_success.html', {
            'result': result,
            'message': "Your account is now active!",
        })

    def generate_uid_number(self):
        """
        Find the last record of user. Get UID base and increment by adding the last record pk
        (primary key) and one
        :return: int
        """
        uid_number = settings.LDAP_BASE_UID
        try:
            latest = User.objects.latest('pk')
            uid_number += latest.pk + 1
        except User.DoesNotExist:
            pass

        return uid_number


class PasswordResetView(generic.FormView):
    template_name = 'user/password_reset.html'
    form_class = PasswordResetForm
    success_url = '/user/password/reset/success/'

    def form_valid(self, form):
        """
        1. get user by the provided email from db (die silently if there's none)
        2. if exists and is active, send reset email
        :param form: 
        :return: 
        """
        passwd_util = PasswordUtils()
        email = form.cleaned_data.get('email')
        user = User.objects.get(email=email)
        user_reg_record = UserRegistrationRecord.objects.get(user=user)
        token = passwd_util.getsalt(length=60) # re-use salt method to generate unique token
        expiry = timezone.now() + timedelta(hours=settings.PASSWORD_RESET_TOKEN_EXPIRY)
        user_reg_record.reset_code = token
        user_reg_record.reset_code_active = True
        user_reg_record.reset_code_expiry = expiry
        user_reg_record.save()

        reset_link = settings.SITE_BASE_URL + '/user/password/edit/' + token + '/'
        # send email
        send_reset_password_email(user.email, settings.DEFAULT_FROM_EMAIL,
                                  user.get_full_name(), reset_link, settings.IDP_NAME)

        return super().form_valid(form)


class PasswordResetSuccessView(generic.TemplateView):
    template_name = 'user/password_reset_success.html'


class PasswordEditView(generic.View):
    template_name = 'user/password_edit.html'

    def get(self, request, token):
        self.check_token_validity(token)
        return render(request, self.template_name, {
            'form': PasswordResetEditForm(),
        })

    def post(self, request, token):
        ldap_ops = LDAPOperations()
        passwd_util = PasswordUtils()
        user_rr = self.check_token_validity(token)

        form = PasswordResetEditForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            username = user_rr.user.username
            password = passwd_util.mkpasswd(data.get('password'), hash='crypt')

            result = ldap_ops.set_password(username, password)
            if result:
                user_rr.reset_code_expiry = timezone.now()
                user_rr.reset_code = ''
                user_rr.reset_code_active = False
                user_rr.ldap_password = password
                user_rr.save()
                return redirect('/user/password/edit/success/')
            else:
                return render(request, self.template_name, {
                    'form': form,
                    'ldap_error': 'Password reset failed on LDAP server. Contact admin'
                })
        else:
            return render(request, self.template_name, {
                'form': form,
            })

    def check_token_validity(self,token):
        try:
            user_rr = UserRegistrationRecord.objects.get(reset_code=token,
                                                         reset_code_active=True,
                                                         reset_code_expiry__gt=timezone.now())
        except UserRegistrationRecord.DoesNotExist:
            raise PasswordResetException('Password reset link invalid or expired')
        return user_rr


class PasswordEditSuccessView(generic.TemplateView):
    template_name = 'user/password_edit_success.html'

user/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ IDP_NAME }}: {% block title %}Welcome! User Registration{% endblock %}</title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    <style type="text/css">
        .invalid-feedback {
         color: red;
         }

    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a href="{% url 'user:index' %}"><img width="200" src="{{IDP_LOGO}}" alt="{{IDP_NAME}}" /></a>
        </div>
        <div class="col-md-10">
            <h1>{{ IDP_NAME }} User Support</h1>
        </div>
    </div>
    {% block wrapper %}
    <h2>Don't have a Federated Identity yet? proceed and register below</h2>
    <a href="{% url 'user:register' %}" class="btn btn-success btn-lg" role="button">Register</a>
    <a href="{% url 'user:password_reset' %}" class="btn btn-warning btn-lg" role="button">Forgot Password</a>
    <p>If you already have a Federated ID, you can test your login credentials at:
        <a href="{{ SERVICE_PROVIDER_URL }}" class="btn btn-danger btn-sm" role="button">{{ SERVICE_PROVIDER }}</a>
    </p>
    {% endblock %}
</div>
</body>
</html>

user/templates/user/password_edit.html
{% extends "user/index.html" %}
{% block title %}Enter New Password{% endblock %}
{% block wrapper %}
<div class="col-md-6">
    {% if ldap_error %}
    <div class="alert alert-danger">
        {{ ldap_error }}
    </div>
    {% endif %}
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

user/templates/user/password_edit_success.html
{% extends "user/index.html" %}
{% block title %}Password edited successfully{% endblock %}
{% block wrapper %}
<h1>Password Edit</h1>
<h2 class="text-success">Your password has been successfully updated. Test your login credentials at
    <a href="{{ SERVICE_PROVIDER_URL }}" class="btn btn-danger btn-sm" role="button">{{ SERVICE_PROVIDER }}</a></h2>
{% endblock %}

user/templates/user/password_reset.html
{% extends "user/index.html" %}
{% block title %}Reset Password{% endblock %}
{% block wrapper %}
<div class="col-md-6">
    <div class="row">
        <h2>Password Reset {{ idp_name }}</h2>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

user/templates/user/password_reset_success.html
{% extends "user/index.html" %}
{% block title %}Password reset sent{% endblock %}
{% block wrapper %}
<h1>Email sent</h1>
<h2 class="text-success">A link has been sent to the email you provided. Follow the instructions</h2>
{% endblock %}

user/templates/user/register.html
{% extends "user/index.html" %}
{% block title %}Create an account{% endblock %}
{% block wrapper %}
    <div class="row">
        <h2>You are registering to the {{ IDP_NAME }}</h2>
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        <b>{{ form.errors|length}}</b> error{{ form.errors|length|pluralize:" was,s were" }} found! Please fix.
        {{ form.non_field_errors }}
        <ul>
		    {% for field in form %}
			{% if field.errors %}<li><i>{{ field.label }}</i>: {{ field.errors|striptags }}</li>{% endif %}
			{% endfor %}
		</ul>
    </div>
    {% endif %}

    <div class="row">
        {% load crispy_forms_tags %}
        {% crispy form %}
    </div>
</div>
{% endblock %}

user/templates/user/register_activate_success.html
{% extends "user/index.html" %}
{% block title %}Account activation success!{% endblock %}
{% block wrapper %}
<h1 class="text-success">{{ message }}</h1>
<h2>Proceed to <a href="{{ SERVICE_PROVIDER_URL }}">{{ SERVICE_PROVIDER }}</a> to try out your login credentials</h2>
{% endblock %}

user/templates/user/register_success.html
{% extends "user/index.html" %}
{% block title %}Account creation success!{% endblock %}
{% block wrapper %}
<h1>Successfully registered!</h1>
<h2 class="text-success">A verification email has been sent to your account</h2>
{% endblock %}